### ISSUE TITLE
Maria Trost – Falsche genonames-ID (place_3e025a812a3b11058ad4e4fdd240b0e5)

### ISSUE THREAD

**Issue by ingoboerner** [acdh-oeaw/schnitzler-tagebuch-data#1]
https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/hits.html?searchkey=place_3e025a812a3b11058ad4e4fdd240b0e5

eventuell https://de.wikipedia.org/wiki/Basilika_Mariatrost; od. Stadtteil von Graz; aber wohl nicht Maria Trost in Südafrika.

https://www.bergfex.at/sommer/steiermark/touren/wanderung/40027,mariatrost--ries--ragnitz/

**Comment by martinantonmueller** [comment]
Behoben in listplace.xml
