### ISSUE TITLE
Interne ID von Arthur Schnitzler im TGB

### ISSUE THREAD

**Issue by ingoboerner** [acdh-oeaw/schnitzler-tagebuch-data#3]
Ist kein richtiges Issue, eher ein fun fact: Zu Arthur Schnitzler selbst kann in den den Tagebuchdaten keine ID finden, kann sein, dass er niemals seinen Namen erwähnt und es deswegen keinen Personeneintrag gibt. Die Personendaten hab' ich nicht überprüft, nur in der Webapp gesucht.
![as_im_tgb](https://user-images.githubusercontent.com/12182347/57998702-e67a3400-7ad2-11e9-998e-223e14a1d95b.jpeg)

**Comment by martinantonmueller** [comment]
Ich vermute eher, dass das nicht indiziert wurde. (Ich indiziere auch Schnitzler in den eigenen Texten nicht.)

**Comment by martinantonmueller** [comment]
Ja, scheint so zu sein:
https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/show.html?document=entry__1880-09-19.xml&searchexpr=Arthur%20Schnitzler
